# Form implementation generated from reading ui file 'kamera.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Kamera_Formu(object):
    def setupUi(self, Kamera_Formu):
        Kamera_Formu.setObjectName("Kamera_Formu")
        Kamera_Formu.resize(803, 624)
        self.btn_open = QtWidgets.QPushButton(Kamera_Formu)
        self.btn_open.setGeometry(QtCore.QRect(70, 50, 93, 28))
        self.btn_open.setObjectName("btn_open")
        self.btn_fotoCekimi = QtWidgets.QPushButton(Kamera_Formu)
        self.btn_fotoCekimi.setGeometry(QtCore.QRect(180, 50, 93, 28))
        self.btn_fotoCekimi.setObjectName("btn_fotoCekimi")
        self.TEXT = QtWidgets.QTextBrowser(Kamera_Formu)
        self.TEXT.setGeometry(QtCore.QRect(310, 30, 401, 81))
        self.TEXT.setObjectName("TEXT")
        self.label_image = QtWidgets.QLabel(Kamera_Formu)
        self.label_image.setGeometry(QtCore.QRect(120, 140, 471, 381))
        self.label_image.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_image.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_image.setLineWidth(5)
        self.label_image.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_image.setObjectName("label_image")

        self.retranslateUi(Kamera_Formu)
        QtCore.QMetaObject.connectSlotsByName(Kamera_Formu)

    def retranslateUi(self, Kamera_Formu):
        _translate = QtCore.QCoreApplication.translate
        Kamera_Formu.setWindowTitle(_translate("Kamera_Formu", "Form"))
        self.btn_open.setText(_translate("Kamera_Formu", "Kamerayı Aç"))
        self.btn_fotoCekimi.setText(_translate("Kamera_Formu", "Fotoğraf Çek"))
        self.label_image.setText(_translate("Kamera_Formu", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Kamera_Formu = QtWidgets.QWidget()
    ui = Ui_Kamera_Formu()
    ui.setupUi(Kamera_Formu)
    Kamera_Formu.show()
    sys.exit(app.exec())
